#!/bin/bash

set -euo pipefail
. /.functions

set_or_default FIXES_DIR "/fixes"

[ ${#} -gt 0 ] || set -- "${FIXES_DIR}"

for DIR in "${@}" ; do
	require_dir_readable "${DIR}"

	doing "Applying fixes from [${DIR}] ..."

	COUNT=0
	while read FIX ; do
		running "Applying ${FIX} ..."
		OUT="$( "${FIX}" 2>&1 )" || fail "Failed to apply the fix from ${FIX} (rc=${?}):\n${OUT}"
		ok "Fix applied!"
		(( ++COUNT ))
	done < <(find "${DIR}" -mindepth 1 -maxdepth 1 -type f -not -name '.*' -not -name '*.disabled' -executable)
	ok "${COUNT} fixes applied from [${DIR}]!"
done
