#!/bin/bash
set -euo pipefail
. /.functions

# Enable debugging ...
set_as_boolean DEBUG
${DEBUG} && set -x

KEY_VAR="ENCRYPTION_KEY"
if [ ${#} -ge 1 ] ; then
	KEY_VAR="${1}"
	is_valid_envvar "${KEY_VAR}" || fail "Invalid variable name [${KEY_VAR}]" 1>&2
fi

set_or_default "${KEY_VAR}"
if [ -n "${!KEY_VAR}" ] ; then
	# Decrypt the value
	exec openssl aes-256-cbc \
		-a -A -salt -iter 5 -d \
		-kfile <(echo -n "${!KEY_VAR}") 2>/dev/null
else
	# Don't decrypt anything ...
	exec cat
fi
