#!/bin/bash

set -euo pipefail
. /.functions

print_for_id()
{
	local ID="${1}"
	local VERSION="${2:-}"

	local OS_SSL_DIR=""
	local OS_SSL_ANCHORS=""
	local OS_SSL_JAVA_CACERTS=""
	local OS_SSL_UPDATE_CMD=()
	local OS_SSL_SUFFIX=""
	local OS_SSL_CA_TRUSTS=""
	case "${ID,,}" in

		ubuntu | debian )
			OS_SSL_DIR="/etc/ssl"
			OS_SSL_ANCHORS="/usr/local/share/ca-certificates"
			local CERTS_HOME="${OS_SSL_DIR}/certs"
			OS_SSL_JAVA_CACERTS="${CERTS_HOME}/java/cacerts"
			OS_SSL_UPDATE_CMD=( /usr/sbin/update-ca-certificates --fresh )
			OS_SSL_SUFFIX="crt"
			OS_SSL_CA_TRUSTS="${CERTS_HOME}/ca-certificates.${OS_SSL_SUFFIX}"
			;;

		rocky | centos | rhel | fedora )
			OS_SSL_DIR="/etc/pki"
			local TRUSTS_HOME="${OS_SSL_DIR}/ca-trust"
			local TRUSTS_EXTRACTED="${TRUSTS_HOME}/extracted"
			OS_SSL_ANCHORS="${TRUSTS_HOME}/source/anchors"
			OS_SSL_JAVA_CACERTS="${TRUSTS_EXTRACTED}/java/cacerts"
			OS_SSL_UPDATE_CMD=( /usr/bin/update-ca-trust extract )
			OS_SSL_SUFFIX="pem"
			OS_SSL_CA_TRUSTS="${TRUSTS_EXTRACTED}/pem/tls-ca-bundle.${OS_SSL_SUFFIX}"
			;;

		* ) return 1 ;;
	esac

	for VAR in "${!OS_SSL_@}" ; do
		declare -p "${VAR}"
	done
	return 0
}

(
	set -euo pipefail
	SOURCED="false"
	for DIR in /etc /usr/lib ; do
		OS_RELEASE="${DIR}/os-release"
		[ -f "${OS_RELEASE}" ] || continue
		. "${OS_RELEASE}" || fail "Failed to source the file ${OS_RELEASE}"
		SOURCED="true"
	done
	as_boolean "${SOURCED}" || fail "Failed to find the os-release files ... can't continue!"

	[ -n "${NAME:-}" ] || NAME="Linux"
	[ -n "${ID:-}" ] || ID="${NAME,,}"
	[ -n "${VERSION_ID:-}" ] || VERSION_ID="unknown"
	[ -n "${VERSION:-}" ] || VERSION="${VERSION_ID}"
	[ -n "${PRETTY_NAME:-}" ] || PRETTY_NAME="${NAME} ${VERSION}"

	# First go for the exact version
	print_for_id "${ID}" "${VERSION}" && exit 0

	ID_LIKE_MSG=""
	if [ -n "${ID_LIKE:-}" ] ; then
		ID_LIKE_MSG=", like [${ID_LIKE}]"
		for ID in ${ID_LIKE} ; do
			print_for_id "${ID_LIKE}" && exit 0
		done
	fi
	fail "Unsupported OS (${ID} ${VERSION}${ID_LIKE_MSG})"
) || exit ${?}
exit 0
