#!/bin/bash

set -euo pipefail
. /.functions

require_dir_readable "${SSL_DIR}"
require_file_readable "${SSL_DIR}/.env"

#
# Init all the SSL-related stuff
#
wait_ssl

require_file_readable "${SSL_CERTIFICATE}"
require_file_readable "${SSL_PRIVATE_KEY}"
require_file_readable "${SSL_PRIVATE_KEY_AES}"
require_file_readable "${SSL_ROOT}"

# Is the certificate properly signed?
CAT=( "${SSL_ROOT}" )
is_file_readable "${SSL_INT}" && CAT=( "${SSL_INT}" "${CAT[@]}" )
OUT="$(openssl verify -CAfile <(cat "${CAT[@]}") "${SSL_CERTIFICATE}" 2>&1)" || fail "OpenSSL verification failed (rc=${?}): ${OUT}"

# Are the secure key and the plaintext key the same?
A="$(openssl rsa -noout -modulus -in "${SSL_PRIVATE_KEY_AES}" -passin file:"${SSL_PASSWORD_FILE}" 2>&1)" || fail "Failed to get the modulus from the encrypted key at [${SSL_PRIVATE_KEY_AES}] (rc=${?}): ${A}"
B="$(openssl rsa -noout -modulus -in "${SSL_PRIVATE_KEY}" 2>&1)" || fail "Failed to get the modulus from the plaintext key at [${SSL_PRIVATE_KEY}] (rc=${?}): ${B}"
[ "${A}" == "${B}" ] || fail "Modulus mismatch between the keys at [${SSL_DIR}]: [${A}] != [${B}]"

# Does the private key match the certificate?
B="$(openssl x509 -noout -modulus -in "${SSL_CERTIFICATE}" 2>&1)" || fail "Failed to get the modulus from the certificate at [${SSL_CERTIFICATE}] (rc=${?}): ${B}"

[ "${A}" == "${B}" ] || fail "Modulus mismatch between the keys at [${SSL_DIR}] and the certificate: [${A}] != [${B}]"

# Hooray!! VERIFIED!
ok "Certificate verified!"
exit 0
